// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nti/nft_transfer_status_detail.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NftTransferStatusDetail struct {
	ReservedKey     string `protobuf:"bytes,1,opt,name=reservedKey,proto3" json:"reservedKey,omitempty"`
	TransferStatus  int32  `protobuf:"varint,2,opt,name=transferStatus,proto3" json:"transferStatus,omitempty"`
	TransactionHash string `protobuf:"bytes,3,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	NftTokenId      string `protobuf:"bytes,4,opt,name=nftTokenId,proto3" json:"nftTokenId,omitempty"`
	NftSrcChain     int32  `protobuf:"varint,5,opt,name=nftSrcChain,proto3" json:"nftSrcChain,omitempty"`
	NftSrcAddr      string `protobuf:"bytes,6,opt,name=nftSrcAddr,proto3" json:"nftSrcAddr,omitempty"`
	NftDestChain    int32  `protobuf:"varint,7,opt,name=nftDestChain,proto3" json:"nftDestChain,omitempty"`
	NftDestAddr     string `protobuf:"bytes,8,opt,name=nftDestAddr,proto3" json:"nftDestAddr,omitempty"`
	ReservedAt      int32  `protobuf:"varint,9,opt,name=reservedAt,proto3" json:"reservedAt,omitempty"`
}

func (m *NftTransferStatusDetail) Reset()         { *m = NftTransferStatusDetail{} }
func (m *NftTransferStatusDetail) String() string { return proto.CompactTextString(m) }
func (*NftTransferStatusDetail) ProtoMessage()    {}
func (*NftTransferStatusDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_8999ace8997f812b, []int{0}
}
func (m *NftTransferStatusDetail) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftTransferStatusDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftTransferStatusDetail.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftTransferStatusDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftTransferStatusDetail.Merge(m, src)
}
func (m *NftTransferStatusDetail) XXX_Size() int {
	return m.Size()
}
func (m *NftTransferStatusDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NftTransferStatusDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NftTransferStatusDetail proto.InternalMessageInfo

func (m *NftTransferStatusDetail) GetReservedKey() string {
	if m != nil {
		return m.ReservedKey
	}
	return ""
}

func (m *NftTransferStatusDetail) GetTransferStatus() int32 {
	if m != nil {
		return m.TransferStatus
	}
	return 0
}

func (m *NftTransferStatusDetail) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *NftTransferStatusDetail) GetNftTokenId() string {
	if m != nil {
		return m.NftTokenId
	}
	return ""
}

func (m *NftTransferStatusDetail) GetNftSrcChain() int32 {
	if m != nil {
		return m.NftSrcChain
	}
	return 0
}

func (m *NftTransferStatusDetail) GetNftSrcAddr() string {
	if m != nil {
		return m.NftSrcAddr
	}
	return ""
}

func (m *NftTransferStatusDetail) GetNftDestChain() int32 {
	if m != nil {
		return m.NftDestChain
	}
	return 0
}

func (m *NftTransferStatusDetail) GetNftDestAddr() string {
	if m != nil {
		return m.NftDestAddr
	}
	return ""
}

func (m *NftTransferStatusDetail) GetReservedAt() int32 {
	if m != nil {
		return m.ReservedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*NftTransferStatusDetail)(nil), "nti.nti.NftTransferStatusDetail")
}

func init() {
	proto.RegisterFile("nti/nft_transfer_status_detail.proto", fileDescriptor_8999ace8997f812b)
}

var fileDescriptor_8999ace8997f812b = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xb1, 0x4a, 0x03, 0x31,
	0x18, 0xc7, 0x2f, 0xd5, 0xb6, 0x36, 0x8a, 0x85, 0x2c, 0x66, 0x0a, 0x47, 0x11, 0x39, 0x97, 0x76,
	0xf0, 0x09, 0xaa, 0x1d, 0x14, 0xc1, 0xa1, 0xd7, 0xc9, 0xe5, 0x88, 0x77, 0x09, 0x0d, 0xca, 0x77,
	0x25, 0xf9, 0x14, 0xfb, 0x16, 0x3e, 0x96, 0x63, 0x17, 0xc1, 0x51, 0xee, 0x5e, 0x44, 0x2e, 0x3d,
	0x25, 0xed, 0x12, 0xc8, 0x8f, 0x7f, 0x7e, 0xff, 0x24, 0x1f, 0x3d, 0x07, 0x34, 0x13, 0xd0, 0x98,
	0xa1, 0x95, 0xe0, 0xb4, 0xb2, 0x99, 0x43, 0x89, 0xaf, 0x2e, 0x2b, 0x14, 0x4a, 0xf3, 0x32, 0x5e,
	0xd9, 0x12, 0x4b, 0xd6, 0x07, 0x34, 0x63, 0x40, 0x33, 0xfa, 0xea, 0xd0, 0xb3, 0x07, 0x8d, 0x8b,
	0x36, 0x9c, 0xfa, 0xec, 0xcc, 0x47, 0x59, 0x4c, 0x8f, 0xad, 0x72, 0xca, 0xbe, 0xa9, 0xe2, 0x5e,
	0xad, 0x39, 0x89, 0x49, 0x32, 0x98, 0x87, 0x88, 0x5d, 0xd0, 0x53, 0xdc, 0x39, 0xc9, 0x3b, 0x31,
	0x49, 0xba, 0xf3, 0x3d, 0xca, 0x12, 0x3a, 0xf4, 0x44, 0xe6, 0x68, 0x4a, 0xb8, 0x95, 0x6e, 0xc9,
	0x0f, 0xbc, 0x6d, 0x1f, 0x33, 0x41, 0x29, 0x68, 0x5c, 0x94, 0xcf, 0x0a, 0xee, 0x0a, 0x7e, 0xe8,
	0x43, 0x01, 0x69, 0xee, 0x04, 0x1a, 0x53, 0x9b, 0xdf, 0x2c, 0xa5, 0x01, 0xde, 0xf5, 0x75, 0x21,
	0x6a, 0x0d, 0xa9, 0xcd, 0xa7, 0x45, 0x61, 0x79, 0xef, 0xdf, 0xd0, 0x12, 0x36, 0xa2, 0x27, 0xa0,
	0x71, 0xa6, 0x1c, 0x6e, 0x15, 0x7d, 0xaf, 0xd8, 0x61, 0x6d, 0x4b, 0xb3, 0xf7, 0x92, 0xa3, 0xed,
	0xcb, 0x03, 0xd4, 0xb4, 0xfc, 0x7d, 0xc4, 0x14, 0xf9, 0xc0, 0x3b, 0x02, 0x72, 0x7d, 0xf9, 0x59,
	0x09, 0xb2, 0xa9, 0x04, 0xf9, 0xa9, 0x04, 0xf9, 0xa8, 0x45, 0xb4, 0xa9, 0x45, 0xf4, 0x5d, 0x8b,
	0xe8, 0x71, 0xd8, 0x0c, 0xe8, 0x7d, 0xd2, 0xac, 0xb8, 0x5e, 0x29, 0xf7, 0xd4, 0xf3, 0x23, 0xb9,
	0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x8a, 0xd1, 0xd4, 0xba, 0x01, 0x00, 0x00,
}

func (m *NftTransferStatusDetail) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftTransferStatusDetail) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftTransferStatusDetail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReservedAt != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.ReservedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.NftDestAddr) > 0 {
		i -= len(m.NftDestAddr)
		copy(dAtA[i:], m.NftDestAddr)
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(len(m.NftDestAddr)))
		i--
		dAtA[i] = 0x42
	}
	if m.NftDestChain != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.NftDestChain))
		i--
		dAtA[i] = 0x38
	}
	if len(m.NftSrcAddr) > 0 {
		i -= len(m.NftSrcAddr)
		copy(dAtA[i:], m.NftSrcAddr)
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(len(m.NftSrcAddr)))
		i--
		dAtA[i] = 0x32
	}
	if m.NftSrcChain != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.NftSrcChain))
		i--
		dAtA[i] = 0x28
	}
	if len(m.NftTokenId) > 0 {
		i -= len(m.NftTokenId)
		copy(dAtA[i:], m.NftTokenId)
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(len(m.NftTokenId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TransactionHash) > 0 {
		i -= len(m.TransactionHash)
		copy(dAtA[i:], m.TransactionHash)
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(len(m.TransactionHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.TransferStatus != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.TransferStatus))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ReservedKey) > 0 {
		i -= len(m.ReservedKey)
		copy(dAtA[i:], m.ReservedKey)
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(len(m.ReservedKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNftTransferStatusDetail(dAtA []byte, offset int, v uint64) int {
	offset -= sovNftTransferStatusDetail(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NftTransferStatusDetail) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReservedKey)
	if l > 0 {
		n += 1 + l + sovNftTransferStatusDetail(uint64(l))
	}
	if m.TransferStatus != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.TransferStatus))
	}
	l = len(m.TransactionHash)
	if l > 0 {
		n += 1 + l + sovNftTransferStatusDetail(uint64(l))
	}
	l = len(m.NftTokenId)
	if l > 0 {
		n += 1 + l + sovNftTransferStatusDetail(uint64(l))
	}
	if m.NftSrcChain != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.NftSrcChain))
	}
	l = len(m.NftSrcAddr)
	if l > 0 {
		n += 1 + l + sovNftTransferStatusDetail(uint64(l))
	}
	if m.NftDestChain != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.NftDestChain))
	}
	l = len(m.NftDestAddr)
	if l > 0 {
		n += 1 + l + sovNftTransferStatusDetail(uint64(l))
	}
	if m.ReservedAt != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.ReservedAt))
	}
	return n
}

func sovNftTransferStatusDetail(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNftTransferStatusDetail(x uint64) (n int) {
	return sovNftTransferStatusDetail(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NftTransferStatusDetail) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNftTransferStatusDetail
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftTransferStatusDetail: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftTransferStatusDetail: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReservedKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferStatus", wireType)
			}
			m.TransferStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TransferStatus |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftTokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftTokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftSrcChain", wireType)
			}
			m.NftSrcChain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NftSrcChain |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftSrcAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftSrcAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftDestChain", wireType)
			}
			m.NftDestChain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NftDestChain |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftDestAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftDestAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedAt", wireType)
			}
			m.ReservedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReservedAt |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNftTransferStatusDetail(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNftTransferStatusDetail(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNftTransferStatusDetail
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNftTransferStatusDetail
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNftTransferStatusDetail
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNftTransferStatusDetail
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNftTransferStatusDetail        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNftTransferStatusDetail          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNftTransferStatusDetail = fmt.Errorf("proto: unexpected end of group")
)
