// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nti/nft_transfer_status_detail.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NftTransferStatusDetail struct {
	SrcChain        int32  `protobuf:"varint,1,opt,name=srcChain,proto3" json:"srcChain,omitempty"`
	SrcAddr         string `protobuf:"bytes,2,opt,name=srcAddr,proto3" json:"srcAddr,omitempty"`
	DestChain       int32  `protobuf:"varint,3,opt,name=destChain,proto3" json:"destChain,omitempty"`
	DestAddr        string `protobuf:"bytes,4,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	Status          int32  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	TransactionHash string `protobuf:"bytes,6,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	TransferredAt   int32  `protobuf:"varint,7,opt,name=transferredAt,proto3" json:"transferredAt,omitempty"`
	ReservedAt      int32  `protobuf:"varint,8,opt,name=reservedAt,proto3" json:"reservedAt,omitempty"`
}

func (m *NftTransferStatusDetail) Reset()         { *m = NftTransferStatusDetail{} }
func (m *NftTransferStatusDetail) String() string { return proto.CompactTextString(m) }
func (*NftTransferStatusDetail) ProtoMessage()    {}
func (*NftTransferStatusDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_8999ace8997f812b, []int{0}
}
func (m *NftTransferStatusDetail) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftTransferStatusDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftTransferStatusDetail.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftTransferStatusDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftTransferStatusDetail.Merge(m, src)
}
func (m *NftTransferStatusDetail) XXX_Size() int {
	return m.Size()
}
func (m *NftTransferStatusDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_NftTransferStatusDetail.DiscardUnknown(m)
}

var xxx_messageInfo_NftTransferStatusDetail proto.InternalMessageInfo

func (m *NftTransferStatusDetail) GetSrcChain() int32 {
	if m != nil {
		return m.SrcChain
	}
	return 0
}

func (m *NftTransferStatusDetail) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *NftTransferStatusDetail) GetDestChain() int32 {
	if m != nil {
		return m.DestChain
	}
	return 0
}

func (m *NftTransferStatusDetail) GetDestAddr() string {
	if m != nil {
		return m.DestAddr
	}
	return ""
}

func (m *NftTransferStatusDetail) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NftTransferStatusDetail) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *NftTransferStatusDetail) GetTransferredAt() int32 {
	if m != nil {
		return m.TransferredAt
	}
	return 0
}

func (m *NftTransferStatusDetail) GetReservedAt() int32 {
	if m != nil {
		return m.ReservedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*NftTransferStatusDetail)(nil), "nti.nti.NftTransferStatusDetail")
}

func init() {
	proto.RegisterFile("nti/nft_transfer_status_detail.proto", fileDescriptor_8999ace8997f812b)
}

var fileDescriptor_8999ace8997f812b = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4a, 0x03, 0x41,
	0x10, 0xc7, 0xb3, 0xd1, 0xdc, 0x25, 0x03, 0x12, 0xd8, 0x42, 0x17, 0x91, 0x25, 0x48, 0x8a, 0xb3,
	0x49, 0x0a, 0x9f, 0x20, 0x6a, 0x61, 0x65, 0x11, 0xad, 0x6c, 0x8e, 0xf5, 0x76, 0x8f, 0x2c, 0xc8,
	0x5e, 0xd8, 0x19, 0x45, 0xdf, 0x42, 0xdf, 0xca, 0x32, 0xa5, 0xa5, 0xdc, 0xbd, 0x88, 0xdc, 0xe4,
	0xc3, 0x8f, 0x66, 0xe1, 0xff, 0xe7, 0xf7, 0x1b, 0x76, 0x06, 0xc6, 0x81, 0xfc, 0x34, 0x94, 0x94,
	0x53, 0x34, 0x01, 0x4b, 0x17, 0x73, 0x24, 0x43, 0x4f, 0x98, 0x5b, 0x47, 0xc6, 0x3f, 0x4e, 0x96,
	0xb1, 0xa2, 0x4a, 0xa6, 0x81, 0xfc, 0x24, 0x90, 0x3f, 0x7d, 0xef, 0xc2, 0xd1, 0x4d, 0x49, 0x77,
	0x1b, 0xf8, 0x96, 0xd9, 0x2b, 0x46, 0xe5, 0x31, 0xf4, 0x31, 0x16, 0x97, 0x0b, 0xe3, 0x83, 0x12,
	0x23, 0x91, 0xf5, 0xe6, 0xbb, 0x2c, 0x15, 0xa4, 0x18, 0x8b, 0x99, 0xb5, 0x51, 0x75, 0x47, 0x22,
	0x1b, 0xcc, 0xb7, 0x51, 0x9e, 0xc0, 0xc0, 0x3a, 0xa4, 0xb5, 0xb6, 0xc7, 0xda, 0x4f, 0xd1, 0xce,
	0x6c, 0x03, 0x8b, 0xfb, 0x2c, 0xee, 0xb2, 0x3c, 0x84, 0x64, 0xfd, 0x57, 0xd5, 0x63, 0x6d, 0x93,
	0x64, 0x06, 0x43, 0x5e, 0xc6, 0x14, 0xe4, 0xab, 0x70, 0x6d, 0x70, 0xa1, 0x12, 0x56, 0xff, 0xd7,
	0x72, 0x0c, 0x07, 0xdb, 0xb5, 0xa3, 0xb3, 0x33, 0x52, 0x29, 0x0f, 0xfa, 0x5b, 0x4a, 0x0d, 0x10,
	0x1d, 0xba, 0xf8, 0xcc, 0x48, 0x9f, 0x91, 0x5f, 0xcd, 0xc5, 0xd9, 0x47, 0xad, 0xc5, 0xaa, 0xd6,
	0xe2, 0xab, 0xd6, 0xe2, 0xad, 0xd1, 0x9d, 0x55, 0xa3, 0x3b, 0x9f, 0x8d, 0xee, 0xdc, 0x0f, 0xdb,
	0xe3, 0xbe, 0x4c, 0xdb, 0x97, 0x5e, 0x97, 0x0e, 0x1f, 0x12, 0x3e, 0xe7, 0xf9, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x42, 0xef, 0x40, 0xdf, 0x76, 0x01, 0x00, 0x00,
}

func (m *NftTransferStatusDetail) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftTransferStatusDetail) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftTransferStatusDetail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReservedAt != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.ReservedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.TransferredAt != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.TransferredAt))
		i--
		dAtA[i] = 0x38
	}
	if len(m.TransactionHash) > 0 {
		i -= len(m.TransactionHash)
		copy(dAtA[i:], m.TransactionHash)
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(len(m.TransactionHash)))
		i--
		dAtA[i] = 0x32
	}
	if m.Status != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if len(m.DestAddr) > 0 {
		i -= len(m.DestAddr)
		copy(dAtA[i:], m.DestAddr)
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(len(m.DestAddr)))
		i--
		dAtA[i] = 0x22
	}
	if m.DestChain != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.DestChain))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SrcAddr) > 0 {
		i -= len(m.SrcAddr)
		copy(dAtA[i:], m.SrcAddr)
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(len(m.SrcAddr)))
		i--
		dAtA[i] = 0x12
	}
	if m.SrcChain != 0 {
		i = encodeVarintNftTransferStatusDetail(dAtA, i, uint64(m.SrcChain))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNftTransferStatusDetail(dAtA []byte, offset int, v uint64) int {
	offset -= sovNftTransferStatusDetail(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NftTransferStatusDetail) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SrcChain != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.SrcChain))
	}
	l = len(m.SrcAddr)
	if l > 0 {
		n += 1 + l + sovNftTransferStatusDetail(uint64(l))
	}
	if m.DestChain != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.DestChain))
	}
	l = len(m.DestAddr)
	if l > 0 {
		n += 1 + l + sovNftTransferStatusDetail(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.Status))
	}
	l = len(m.TransactionHash)
	if l > 0 {
		n += 1 + l + sovNftTransferStatusDetail(uint64(l))
	}
	if m.TransferredAt != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.TransferredAt))
	}
	if m.ReservedAt != 0 {
		n += 1 + sovNftTransferStatusDetail(uint64(m.ReservedAt))
	}
	return n
}

func sovNftTransferStatusDetail(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNftTransferStatusDetail(x uint64) (n int) {
	return sovNftTransferStatusDetail(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NftTransferStatusDetail) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNftTransferStatusDetail
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftTransferStatusDetail: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftTransferStatusDetail: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcChain", wireType)
			}
			m.SrcChain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SrcChain |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChain", wireType)
			}
			m.DestChain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestChain |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransactionHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferredAt", wireType)
			}
			m.TransferredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TransferredAt |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedAt", wireType)
			}
			m.ReservedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReservedAt |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNftTransferStatusDetail(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNftTransferStatusDetail
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNftTransferStatusDetail(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNftTransferStatusDetail
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNftTransferStatusDetail
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNftTransferStatusDetail
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNftTransferStatusDetail
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNftTransferStatusDetail
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNftTransferStatusDetail        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNftTransferStatusDetail          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNftTransferStatusDetail = fmt.Errorf("proto: unexpected end of group")
)
