// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nti/reserved_nft_transfer.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReservedNftTransfer struct {
	ReservedKey         string `protobuf:"bytes,1,opt,name=reservedKey,proto3" json:"reservedKey,omitempty"`
	SrcNftHash          string `protobuf:"bytes,2,opt,name=srcNftHash,proto3" json:"srcNftHash,omitempty"`
	SrcChain            string `protobuf:"bytes,3,opt,name=srcChain,proto3" json:"srcChain,omitempty"`
	SrcAddr             string `protobuf:"bytes,4,opt,name=srcAddr,proto3" json:"srcAddr,omitempty"`
	DestChain           string `protobuf:"bytes,5,opt,name=destChain,proto3" json:"destChain,omitempty"`
	DestAddr            string `protobuf:"bytes,6,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	DestReservationAddr string `protobuf:"bytes,7,opt,name=destReservationAddr,proto3" json:"destReservationAddr,omitempty"`
	BlockHeight         int32  `protobuf:"varint,8,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	FungibleToken       int32  `protobuf:"varint,9,opt,name=fungibleToken,proto3" json:"fungibleToken,omitempty"`
	CreatedAt           int32  `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (m *ReservedNftTransfer) Reset()         { *m = ReservedNftTransfer{} }
func (m *ReservedNftTransfer) String() string { return proto.CompactTextString(m) }
func (*ReservedNftTransfer) ProtoMessage()    {}
func (*ReservedNftTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_387170ed3b286efd, []int{0}
}
func (m *ReservedNftTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReservedNftTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReservedNftTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReservedNftTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservedNftTransfer.Merge(m, src)
}
func (m *ReservedNftTransfer) XXX_Size() int {
	return m.Size()
}
func (m *ReservedNftTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservedNftTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_ReservedNftTransfer proto.InternalMessageInfo

func (m *ReservedNftTransfer) GetReservedKey() string {
	if m != nil {
		return m.ReservedKey
	}
	return ""
}

func (m *ReservedNftTransfer) GetSrcNftHash() string {
	if m != nil {
		return m.SrcNftHash
	}
	return ""
}

func (m *ReservedNftTransfer) GetSrcChain() string {
	if m != nil {
		return m.SrcChain
	}
	return ""
}

func (m *ReservedNftTransfer) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *ReservedNftTransfer) GetDestChain() string {
	if m != nil {
		return m.DestChain
	}
	return ""
}

func (m *ReservedNftTransfer) GetDestAddr() string {
	if m != nil {
		return m.DestAddr
	}
	return ""
}

func (m *ReservedNftTransfer) GetDestReservationAddr() string {
	if m != nil {
		return m.DestReservationAddr
	}
	return ""
}

func (m *ReservedNftTransfer) GetBlockHeight() int32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ReservedNftTransfer) GetFungibleToken() int32 {
	if m != nil {
		return m.FungibleToken
	}
	return 0
}

func (m *ReservedNftTransfer) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*ReservedNftTransfer)(nil), "nti.nti.ReservedNftTransfer")
}

func init() { proto.RegisterFile("nti/reserved_nft_transfer.proto", fileDescriptor_387170ed3b286efd) }

var fileDescriptor_387170ed3b286efd = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x3b, 0xfd, 0xbe, 0x36, 0xcd, 0x88, 0x08, 0xd3, 0xcd, 0x20, 0x32, 0x06, 0x71, 0x51,
	0x37, 0xad, 0xe0, 0x13, 0x54, 0x37, 0x05, 0xa1, 0x8b, 0xd0, 0x95, 0x9b, 0x92, 0x3f, 0x37, 0xcd,
	0xd0, 0x32, 0x29, 0x33, 0x57, 0xb1, 0x6f, 0xe1, 0x63, 0xb9, 0xec, 0xd2, 0x9d, 0x92, 0xbc, 0x88,
	0xcc, 0xa4, 0xb1, 0x11, 0xdc, 0x84, 0x9c, 0x73, 0x7e, 0xe7, 0x32, 0x97, 0x4b, 0x2f, 0x15, 0xca,
	0x89, 0x06, 0x03, 0xfa, 0x05, 0xd2, 0xa5, 0xca, 0x70, 0x89, 0x3a, 0x52, 0x26, 0x03, 0x3d, 0xde,
	0xea, 0x02, 0x0b, 0xe6, 0x29, 0x94, 0x63, 0x85, 0xf2, 0xea, 0xb3, 0x4b, 0x87, 0xe1, 0x01, 0x9c,
	0x67, 0xb8, 0x38, 0x60, 0x2c, 0xa0, 0x27, 0x4d, 0xff, 0x11, 0x76, 0x9c, 0x04, 0x64, 0xe4, 0x87,
	0x6d, 0x8b, 0x09, 0x4a, 0x8d, 0x4e, 0xe6, 0x19, 0xce, 0x22, 0x93, 0xf3, 0xae, 0x03, 0x5a, 0x0e,
	0x3b, 0xa7, 0x03, 0xa3, 0x93, 0x87, 0x3c, 0x92, 0x8a, 0xff, 0x73, 0xe9, 0x8f, 0x66, 0x9c, 0x7a,
	0x46, 0x27, 0xd3, 0x34, 0xd5, 0xfc, 0xbf, 0x8b, 0x1a, 0xc9, 0x2e, 0xa8, 0x9f, 0x82, 0xc1, 0xba,
	0xd6, 0x73, 0xd9, 0xd1, 0xb0, 0x33, 0xad, 0x70, 0xc5, 0x7e, 0x3d, 0xb3, 0xd1, 0xec, 0x96, 0x0e,
	0xed, 0x7f, 0xbd, 0x4c, 0x84, 0xb2, 0x50, 0x0e, 0xf3, 0x1c, 0xf6, 0x57, 0x64, 0x77, 0x8c, 0x37,
	0x45, 0xb2, 0x9e, 0x81, 0x5c, 0xe5, 0xc8, 0x07, 0x01, 0x19, 0xf5, 0xc2, 0xb6, 0xc5, 0xae, 0xe9,
	0x69, 0xf6, 0xac, 0x56, 0x32, 0xde, 0xc0, 0xa2, 0x58, 0x83, 0xe2, 0xbe, 0x63, 0x7e, 0x9b, 0xf6,
	0xcd, 0x89, 0x86, 0x08, 0x21, 0x9d, 0x22, 0xa7, 0x8e, 0x38, 0x1a, 0xf7, 0x37, 0xef, 0xa5, 0x20,
	0xfb, 0x52, 0x90, 0xaf, 0x52, 0x90, 0xb7, 0x4a, 0x74, 0xf6, 0x95, 0xe8, 0x7c, 0x54, 0xa2, 0xf3,
	0x74, 0x66, 0xaf, 0xf4, 0x3a, 0xb1, 0x5f, 0xdc, 0x6d, 0xc1, 0xc4, 0x7d, 0x77, 0x9c, 0xbb, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0xd1, 0x4e, 0x72, 0xbf, 0x01, 0x00, 0x00,
}

func (m *ReservedNftTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReservedNftTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReservedNftTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x50
	}
	if m.FungibleToken != 0 {
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(m.FungibleToken))
		i--
		dAtA[i] = 0x48
	}
	if m.BlockHeight != 0 {
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.DestReservationAddr) > 0 {
		i -= len(m.DestReservationAddr)
		copy(dAtA[i:], m.DestReservationAddr)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.DestReservationAddr)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.DestAddr) > 0 {
		i -= len(m.DestAddr)
		copy(dAtA[i:], m.DestAddr)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.DestAddr)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DestChain) > 0 {
		i -= len(m.DestChain)
		copy(dAtA[i:], m.DestChain)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.DestChain)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SrcAddr) > 0 {
		i -= len(m.SrcAddr)
		copy(dAtA[i:], m.SrcAddr)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.SrcAddr)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SrcChain) > 0 {
		i -= len(m.SrcChain)
		copy(dAtA[i:], m.SrcChain)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.SrcChain)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SrcNftHash) > 0 {
		i -= len(m.SrcNftHash)
		copy(dAtA[i:], m.SrcNftHash)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.SrcNftHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ReservedKey) > 0 {
		i -= len(m.ReservedKey)
		copy(dAtA[i:], m.ReservedKey)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.ReservedKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintReservedNftTransfer(dAtA []byte, offset int, v uint64) int {
	offset -= sovReservedNftTransfer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReservedNftTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReservedKey)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.SrcNftHash)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.SrcChain)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.SrcAddr)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.DestChain)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.DestAddr)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.DestReservationAddr)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovReservedNftTransfer(uint64(m.BlockHeight))
	}
	if m.FungibleToken != 0 {
		n += 1 + sovReservedNftTransfer(uint64(m.FungibleToken))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovReservedNftTransfer(uint64(m.CreatedAt))
	}
	return n
}

func sovReservedNftTransfer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReservedNftTransfer(x uint64) (n int) {
	return sovReservedNftTransfer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReservedNftTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReservedNftTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReservedNftTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReservedNftTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReservedKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcNftHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcNftHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SrcAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SrcAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestReservationAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestReservationAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FungibleToken", wireType)
			}
			m.FungibleToken = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FungibleToken |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReservedNftTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReservedNftTransfer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReservedNftTransfer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReservedNftTransfer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReservedNftTransfer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReservedNftTransfer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReservedNftTransfer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReservedNftTransfer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReservedNftTransfer = fmt.Errorf("proto: unexpected end of group")
)
