// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nti/reserved_nft_transfer.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReservedNftTransfer struct {
	ReservedKey   string `protobuf:"bytes,1,opt,name=reservedKey,proto3" json:"reservedKey,omitempty"`
	NftSrcHash    string `protobuf:"bytes,2,opt,name=nftSrcHash,proto3" json:"nftSrcHash,omitempty"`
	NftSrcChain   string `protobuf:"bytes,3,opt,name=nftSrcChain,proto3" json:"nftSrcChain,omitempty"`
	NftSrcAddr    string `protobuf:"bytes,4,opt,name=nftSrcAddr,proto3" json:"nftSrcAddr,omitempty"`
	NftDestChain  string `protobuf:"bytes,5,opt,name=nftDestChain,proto3" json:"nftDestChain,omitempty"`
	NftDestAddr   string `protobuf:"bytes,6,opt,name=nftDestAddr,proto3" json:"nftDestAddr,omitempty"`
	FtChain       string `protobuf:"bytes,7,opt,name=ftChain,proto3" json:"ftChain,omitempty"`
	FtSrcAddr     string `protobuf:"bytes,8,opt,name=ftSrcAddr,proto3" json:"ftSrcAddr,omitempty"`
	FtDestAddr    string `protobuf:"bytes,9,opt,name=ftDestAddr,proto3" json:"ftDestAddr,omitempty"`
	FungibleToken int32  `protobuf:"varint,10,opt,name=fungibleToken,proto3" json:"fungibleToken,omitempty"`
	BlockHeight   int32  `protobuf:"varint,11,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	CreatedAt     int32  `protobuf:"varint,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (m *ReservedNftTransfer) Reset()         { *m = ReservedNftTransfer{} }
func (m *ReservedNftTransfer) String() string { return proto.CompactTextString(m) }
func (*ReservedNftTransfer) ProtoMessage()    {}
func (*ReservedNftTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_387170ed3b286efd, []int{0}
}
func (m *ReservedNftTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReservedNftTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReservedNftTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReservedNftTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservedNftTransfer.Merge(m, src)
}
func (m *ReservedNftTransfer) XXX_Size() int {
	return m.Size()
}
func (m *ReservedNftTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservedNftTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_ReservedNftTransfer proto.InternalMessageInfo

func (m *ReservedNftTransfer) GetReservedKey() string {
	if m != nil {
		return m.ReservedKey
	}
	return ""
}

func (m *ReservedNftTransfer) GetNftSrcHash() string {
	if m != nil {
		return m.NftSrcHash
	}
	return ""
}

func (m *ReservedNftTransfer) GetNftSrcChain() string {
	if m != nil {
		return m.NftSrcChain
	}
	return ""
}

func (m *ReservedNftTransfer) GetNftSrcAddr() string {
	if m != nil {
		return m.NftSrcAddr
	}
	return ""
}

func (m *ReservedNftTransfer) GetNftDestChain() string {
	if m != nil {
		return m.NftDestChain
	}
	return ""
}

func (m *ReservedNftTransfer) GetNftDestAddr() string {
	if m != nil {
		return m.NftDestAddr
	}
	return ""
}

func (m *ReservedNftTransfer) GetFtChain() string {
	if m != nil {
		return m.FtChain
	}
	return ""
}

func (m *ReservedNftTransfer) GetFtSrcAddr() string {
	if m != nil {
		return m.FtSrcAddr
	}
	return ""
}

func (m *ReservedNftTransfer) GetFtDestAddr() string {
	if m != nil {
		return m.FtDestAddr
	}
	return ""
}

func (m *ReservedNftTransfer) GetFungibleToken() int32 {
	if m != nil {
		return m.FungibleToken
	}
	return 0
}

func (m *ReservedNftTransfer) GetBlockHeight() int32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ReservedNftTransfer) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*ReservedNftTransfer)(nil), "nti.nti.ReservedNftTransfer")
}

func init() { proto.RegisterFile("nti/reserved_nft_transfer.proto", fileDescriptor_387170ed3b286efd) }

var fileDescriptor_387170ed3b286efd = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4e, 0xc2, 0x40,
	0x14, 0x86, 0x19, 0x11, 0x90, 0x01, 0x63, 0x32, 0x6e, 0x66, 0x61, 0x46, 0x42, 0x5c, 0xe0, 0x06,
	0x16, 0x9e, 0x00, 0x75, 0x41, 0x62, 0xe2, 0x02, 0x59, 0xb9, 0x21, 0xa5, 0x7d, 0x43, 0x27, 0x90,
	0x29, 0x99, 0x3e, 0x8d, 0xdc, 0xc2, 0x0b, 0x78, 0x1f, 0x97, 0x2c, 0x5d, 0x9a, 0xf6, 0x22, 0x66,
	0xa6, 0xad, 0x1d, 0x36, 0x4d, 0xde, 0xf7, 0xfe, 0x7e, 0xef, 0x4f, 0x86, 0x5e, 0x6b, 0x54, 0x13,
	0x03, 0x29, 0x98, 0x77, 0x88, 0x96, 0x5a, 0xe2, 0x12, 0x4d, 0xa0, 0x53, 0x09, 0x66, 0xbc, 0x33,
	0x09, 0x26, 0xac, 0xa3, 0x51, 0x8d, 0x35, 0xaa, 0xe1, 0x57, 0x93, 0x5e, 0xce, 0xcb, 0xe0, 0xb3,
	0xc4, 0x45, 0x19, 0x63, 0x03, 0xda, 0xab, 0xfe, 0x7f, 0x82, 0x3d, 0x27, 0x03, 0x32, 0xea, 0xce,
	0x7d, 0xc4, 0x04, 0xa5, 0x5a, 0xe2, 0x8b, 0x09, 0x67, 0x41, 0x1a, 0xf3, 0x13, 0x17, 0xf0, 0x88,
	0x35, 0x14, 0xd3, 0x43, 0x1c, 0x28, 0xcd, 0x9b, 0x85, 0xc1, 0x43, 0xb5, 0x61, 0x1a, 0x45, 0x86,
	0x9f, 0xfa, 0x06, 0x4b, 0xd8, 0x90, 0xf6, 0xb5, 0xc4, 0x47, 0x48, 0xb1, 0x50, 0xb4, 0x5c, 0xe2,
	0x88, 0x95, 0x57, 0xec, 0xec, 0x24, 0xed, 0xff, 0x2b, 0x15, 0x62, 0x9c, 0x76, 0x64, 0x29, 0xe8,
	0xb8, 0x6d, 0x35, 0xb2, 0x2b, 0xda, 0xad, 0xcf, 0x9f, 0xb9, 0x5d, 0x0d, 0x6c, 0x3b, 0x4f, 0xdc,
	0x2d, 0xda, 0x79, 0xde, 0x1b, 0x7a, 0x2e, 0xdf, 0xf4, 0x5a, 0xad, 0xb6, 0xb0, 0x48, 0x36, 0xa0,
	0x39, 0x1d, 0x90, 0x51, 0x6b, 0x7e, 0x0c, 0x6d, 0xbf, 0xd5, 0x36, 0x09, 0x37, 0x33, 0x50, 0xeb,
	0x18, 0x79, 0xcf, 0x65, 0x7c, 0x64, 0x5b, 0x84, 0x06, 0x02, 0x84, 0x68, 0x8a, 0xbc, 0xef, 0xf6,
	0x35, 0xb8, 0xbf, 0xfd, 0xce, 0x04, 0x39, 0x64, 0x82, 0xfc, 0x66, 0x82, 0x7c, 0xe6, 0xa2, 0x71,
	0xc8, 0x45, 0xe3, 0x27, 0x17, 0x8d, 0xd7, 0x0b, 0xfb, 0xc6, 0x1f, 0x13, 0xfb, 0xc5, 0xfd, 0x0e,
	0xd2, 0x55, 0xdb, 0x3d, 0xed, 0xdd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0x26, 0xfb, 0xeb,
	0xfd, 0x01, 0x00, 0x00,
}

func (m *ReservedNftTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReservedNftTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReservedNftTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x60
	}
	if m.BlockHeight != 0 {
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x58
	}
	if m.FungibleToken != 0 {
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(m.FungibleToken))
		i--
		dAtA[i] = 0x50
	}
	if len(m.FtDestAddr) > 0 {
		i -= len(m.FtDestAddr)
		copy(dAtA[i:], m.FtDestAddr)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.FtDestAddr)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.FtSrcAddr) > 0 {
		i -= len(m.FtSrcAddr)
		copy(dAtA[i:], m.FtSrcAddr)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.FtSrcAddr)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.FtChain) > 0 {
		i -= len(m.FtChain)
		copy(dAtA[i:], m.FtChain)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.FtChain)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.NftDestAddr) > 0 {
		i -= len(m.NftDestAddr)
		copy(dAtA[i:], m.NftDestAddr)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.NftDestAddr)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.NftDestChain) > 0 {
		i -= len(m.NftDestChain)
		copy(dAtA[i:], m.NftDestChain)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.NftDestChain)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.NftSrcAddr) > 0 {
		i -= len(m.NftSrcAddr)
		copy(dAtA[i:], m.NftSrcAddr)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.NftSrcAddr)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.NftSrcChain) > 0 {
		i -= len(m.NftSrcChain)
		copy(dAtA[i:], m.NftSrcChain)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.NftSrcChain)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NftSrcHash) > 0 {
		i -= len(m.NftSrcHash)
		copy(dAtA[i:], m.NftSrcHash)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.NftSrcHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ReservedKey) > 0 {
		i -= len(m.ReservedKey)
		copy(dAtA[i:], m.ReservedKey)
		i = encodeVarintReservedNftTransfer(dAtA, i, uint64(len(m.ReservedKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintReservedNftTransfer(dAtA []byte, offset int, v uint64) int {
	offset -= sovReservedNftTransfer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReservedNftTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReservedKey)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.NftSrcHash)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.NftSrcChain)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.NftSrcAddr)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.NftDestChain)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.NftDestAddr)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.FtChain)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.FtSrcAddr)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	l = len(m.FtDestAddr)
	if l > 0 {
		n += 1 + l + sovReservedNftTransfer(uint64(l))
	}
	if m.FungibleToken != 0 {
		n += 1 + sovReservedNftTransfer(uint64(m.FungibleToken))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovReservedNftTransfer(uint64(m.BlockHeight))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovReservedNftTransfer(uint64(m.CreatedAt))
	}
	return n
}

func sovReservedNftTransfer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReservedNftTransfer(x uint64) (n int) {
	return sovReservedNftTransfer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReservedNftTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReservedNftTransfer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReservedNftTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReservedNftTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReservedKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftSrcHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftSrcHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftSrcChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftSrcChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftSrcAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftSrcAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftDestChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftDestChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftDestAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftDestAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FtChain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FtChain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FtSrcAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FtSrcAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FtDestAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FtDestAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FungibleToken", wireType)
			}
			m.FungibleToken = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FungibleToken |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReservedNftTransfer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReservedNftTransfer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReservedNftTransfer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReservedNftTransfer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReservedNftTransfer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReservedNftTransfer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReservedNftTransfer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReservedNftTransfer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReservedNftTransfer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReservedNftTransfer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReservedNftTransfer = fmt.Errorf("proto: unexpected end of group")
)
